In [1]:
import numpy as np

print(np.version)

<module 'numpy.version' from 'd:\\dev\\python\\program\\learning\\GEN AI\\python\\numpy_learning\\.venv\\Lib\\site-packages\\numpy\\version.py'>


### basic array in numpy

#### 1D 2D 3D Array with example 

In [12]:
D1 =np.array([1,2,3,4,5,6,7,8,9]) 
D2 = np.array([[1,2,3,4],[1,2,3,4]])
D3 = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
D3

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

### built-in  creators

In [31]:
a = np.zeros([3,4],dtype="int")
a.dtype

dtype('int64')

In [16]:
a = np.ones([3,4])
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
a = np.full((4,2),7)
a

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [20]:
a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [21]:
a = np.linspace(0,1,7)
a

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [23]:
a = np.random.rand(2,3)
a

array([[0.57997879, 0.36980817, 0.27972934],
       [0.60778407, 0.31191226, 0.28506723]])

In [24]:
a = np.random.randint(1,10,(2,3))
a

array([[1, 9, 3],
       [9, 6, 1]], dtype=int32)

## numpy imp formulas

In [ ]:

arr = np.arange(1,9)
    

arr[1:3]

array([2, 3])

In [5]:
arr[::2]

array([1, 3, 5, 7])

In [9]:
arr2 = np.random.rand(3,3)*100
arr2

array([[57.25186856, 55.37368328, 20.66237772],
       [27.55964876,  2.40620571, 41.71579404],
       [33.84581293, 33.00571526, 46.77243546]])

In [20]:
arr2[0,1]

np.float64(55.373683283822714)

In [22]:
arr2[0:2,0:2]

array([[57.25186856, 55.37368328],
       [27.55964876,  2.40620571]])

 # re-Shaping

In [28]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
data1 = a.reshape(2,2,3)
data2 = a.reshape(3,4)
data1 
data2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
d = a.reshape(-1, 3)
d        


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# Stacking & Splitting 


In [39]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6])

In [41]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

In [42]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([a,b]) # same like hstack

array([1, 2, 3, 4, 5, 6])

## splitting

In [47]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
np.vsplit(m,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [49]:
np.hsplit(m,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

# Boolean & Fancy Indexing 


In [50]:
a= np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:

mark = 4 > a
mark


array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [52]:
a[mark]

array([0, 1, 2, 3])

In [53]:
final = a[a * 2 == 4]
final

array([2])

In [54]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 
a

array([[1, 2],
       [3, 4]])

In [55]:
b

array([[5, 6],
       [7, 8]])

In [56]:
a*b

array([[ 5, 12],
       [21, 32]])

In [57]:
a@b

array([[19, 22],
       [43, 50]])

In [59]:
data = np.random.seed(42)
data

In [60]:
np.random.rand(3, 3) 

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

In [66]:
np.random.randint(2,200,20)

array([ 10,  89, 130, 137,  64, 140,  82, 137, 164, 164,  34, 124,   6,
        42,  29, 136,  73,  13, 163,  34], dtype=int32)

In [62]:
np.random.randn(3, 3) 

array([[-1.72491783, -0.56228753, -1.01283112],
       [ 0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 ]])

In [70]:
a = np.random.rand(3,3)*100
data =np.random.shuffle(a)
data
