In [6]:
import numpy as np

print(np.version)

<module 'numpy.version' from 'd:\\dev\\python\\program\\learning\\GEN AI\\python\\numpy_learning\\.venv\\Lib\\site-packages\\numpy\\version.py'>


### basic array in numpy

#### 1D 2D 3D Array with example 

In [12]:
D1 =np.array([1,2,3,4,5,6,7,8,9]) 
D2 = np.array([[1,2,3,4],[1,2,3,4]])
D3 = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
D3

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

### built-in  creators

In [31]:
a = np.zeros([3,4],dtype="int")
a.dtype

dtype('int64')

In [16]:
a = np.ones([3,4])
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
a = np.full((4,2),7)
a

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [20]:
a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [21]:
a = np.linspace(0,1,7)
a

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [23]:
a = np.random.rand(2,3)
a

array([[0.57997879, 0.36980817, 0.27972934],
       [0.60778407, 0.31191226, 0.28506723]])

In [24]:
a = np.random.randint(1,10,(2,3))
a

array([[1, 9, 3],
       [9, 6, 1]], dtype=int32)